### ISSUE TITLE
Should we launch Taco app with slashing?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#104]
Or alternatively, deactivate slashing by tuning the parameters?

**Comment by vzotova** [comment]
Small remark, to deactivate we can skip setting adjudicator

**Comment by jMyles** [comment]
I thought we had decided we were initially not going to slash.

Somewhere we made a little list of things we can slash for... or was that on a call?  Do you remember where that was?

Without thinking too hard about it, it seems to me we're better off adding slashing later, after some successes and failures.

**Comment by derekpierre** [comment]
No slashing at launch.
