### ISSUE TITLE
Python and solidity linter GH action

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#12]

**Comment by anantasty** [comment]
Do you have a preference for python linter? Pylint?

**Comment by cygnusv** [comment]
I don't have a preference, personally. What about you @KPrasch @vzotova @manumonti ?

**Comment by anantasty** [comment]
Created #21 which adds Solhint and Pylint for linters. Still needs more configuration. What are your suggestion @cygnusv @KPrasch @vzotova @manumonti
