### ISSUE TITLE
Use GitHub workflow to automatize uploading of NPM package

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-contracts#125]
The deployment artifacts for the different networks are stored in NPM package

https://www.npmjs.com/package/@nucypher/nucypher-contracts/v/0.4.0-goerli?activeTab=versions

Up to now, the process of uploading the new artifacts is manual:

https://github.com/nucypher/nucypher-contracts/blob/972ca1a6983a3d0fbc5e7966a0f333715f64f97d/README.md#npm-publishing-process

As base, we can take @threshold-network/solidity-contracts:

https://github.com/threshold-network/solidity-contracts/blob/38debeb9d5dc487a6949d9b21297a8a68ccb5312/.github/workflows/contracts.yml

1. The CI checks every day if there are new contracts to deploy by checking the dapp-development branch.
    If this is the case or the workflow is manually triggered:
2. Contracts are built and deployed in the corresponding testnet.
3. Contracts are verified in Etherscan.
4. NPM package version is updated (new version number that ends in -<testnet>)
5. NPM package with contract artifacts is uploaded.

**Comment by KPrasch** [comment]
closed by #146
