### ISSUE TITLE
Missing commitment extensions in initial TACoApplication deployment.

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#215]
From the [TIP-062 post](https://forum.threshold.network/t/tip-062-taco-threshold-access-control-added-as-threshold-application-lock-up-bonus-pre-folded-into-taco/703):
```
Functionally, stakers will be able to choose between discrete lock-up periods and receive a commensurate bonus:

9 months total (6 month deauth delay + 3 month extension): 0.5% extra yield
12 months total (6 month deauth delay + 6 month extension): 1% extra yield
18 months total (6 month deauth delay + 12 month extension): 2% extra yield
24 months total (6 month deauth delay + 18 month extension): 3% extra yield
```
However, when deploying the contract, it turns out we only set it for 6 and 12 month extensions, so we need to upgrade the contract with the correct list of parameters.

**Comment by derekpierre** [comment]
So is 6 months really supposed to be 9 months i.e. 6-months is not a valid option?
