### ISSUE TITLE
isPolicyActive() function issue in Subscription Manager contract

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-contracts#22]
`isPolicyActive()` function of [SubscriptionManager.sol](https://github.com/nucypher/nucypher-contracts/blob/e1759282155695aa733a4cfb97a943a1a94a4367/contracts/matic/SubscriptionManager.sol#L130) only checks if the policy has "expired" or not, but the function will return true if the policy has been created but has not yet started.

So, in my opinion, it could be a bit confusing since a policy that has been created but still it is not started shouldn't has the status of "active".

**Comment by fjarri** [comment]
Just a note, stemming from a discussion on Discord: the current logic allows one to create super-cheap 1-second policies that are nevertheless considered active for an arbitrary amount of time.
