### ISSUE TITLE
Explanation of test failing/passing

### ISSUE THREAD

**Issue by theref** [nucypher/nucypher-contracts#32]
I don't understand why this test passes.

https://github.com/nucypher/nucypher-contracts/blob/3287a4778258ff3a517981c412382054c203bb9d/tests/test_token.py#L90

We do the exact same approval on L66, what has changed that would cause the approval to revert? @cygnusv @vzotova

**Comment by vzotova** [comment]
This line in `ERC20.approve`:
`require(value == 0 || _allowed[msg.sender][spender] == 0);`
It's not 100% canonical for ERC20 but pretty common protection from malicious using allowance.

**Comment by theref** [comment]
Thank you, makes complete sense
