### ISSUE TITLE
Replicate Nucypher Deployers with brownie

### ISSUE THREAD

**Issue by theref** [nucypher/nucypher-contracts#38]
All the logic from https://github.com/nucypher/nucypher/blob/development/nucypher/blockchain/eth/deployers.py needs to be implemented in this repo

- [x] Deployer for Staking Escrow #39
- [x] NuCypher Token #48 
~~Adjudicator #49~~
- [x] Deployer for PRE Application #40

**Comment by cygnusv** [comment]
Not all the logic is needed. In fact, it would be better to use `deployers.py` just as a reference, but focusing on the fundamentals. In particular, for StakingEscrow we only need to be able to deploy new implementation contracts (nothing related to upgrades or interactions with Dispatchers)
