### ISSUE TITLE
Threshold Network Application contract high-level decisions/design

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher-contracts#64]
fully-fledged application (like tbtc) 
to enable among other things: https://github.com/nucypher/ferveo/issues/64
also related to https://github.com/nucypher/placeholder/issues/2

**Comment by cygnusv** [comment]
See also https://github.com/nucypher/nucypher-contracts/issues/69

**Comment by cygnusv** [comment]
Consider widening the scope of this contract to be the `ThresholdAccessControlApplication` contract, enabling both CBD/PRE services. Two reasons for this:
- We currently have support in the nucypher client for single operator/ursula for both PRE/CBD
- There's no real application contract for PRE, so if we deploy a new app, we don't want to create a situation where a real app and "fake" app co-exist

**Comment by arjunhassard** [comment]
Reasons from [service + demand]-side perspectives – if we start decoupling PRE & CBD into two independent applications, this will add friction (at the very least cognitive load) for stakers, who will have to assess the cost-benefit of separately authorizing to PRE, and pay for another instance, stay on top of more updates, etc. 

If we try to reduce this friction by making staker constraints identical or similar to CBD (e.g. min lock up time, min stake etc.), then it forgoes one of the advantages of splitting them in the first place. Ultimately, PRE's niche utility means piggybacking on CBD is probably the best way to avoid the app slipping into a cold start issue – with basically no downside for stakers.

**Comment by cygnusv** [comment]
Closed by #99
