### ISSUE TITLE
L1<->L2 state synchronization

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#69]
An implication of our cross-chain coordination contract approach (for reference, 1 stake state contract in Ethereum Mainnet, multiple Coordinator contract in L2s/sidechains), is that we will require certain degree on synchronization between both sides. 

Some examples:
* When initiating a DKG ritual, a L2 Coordinator needs to be sure that the operator correspond to a valid staker (i.e., at least min stake, app is authorized, etc)
* When orderly cohort refreshes occur, e.g., due to a staker unstaking (see https://github.com/nucypher/tdec/issues/123)
* When the result of a ritual produces proof of misbehavior (which can imply slashing on L1)

We need a "common" approach to bridge this communication, taking into consideration also that every L2 may have different messaging strategies.

For example, the L1->L2 step seems to be usually "easy" (i.e., not expensive, and relatively fast): 
* Matic: It only requires to implement some standard methods in the respective Mainnet and Matic contracts, and every call on the mainnet side is bridged to the Matic side when Matic validators sync state. See https://wiki.polygon.technology/docs/develop/l1-l2-communication/state-transfer#state-transfer-from-ethereum--polygon
* Optimism: Similar approach, syncing takes approximately 15 minutes. See https://community.optimism.io/docs/developers/bridge/messaging/#for-ethereum-l1-to-optimism-l2-transactions

The L2->L1 step it's also possible but seems more involved, and I'd say we want to find approaches that reduce this communication as possible.

**Comment by cygnusv** [comment]
Tentative design, with the goal of abstracting away cross-chain complexity from both the CBD application contract and the L2 Coordinators. Complexity is hidden the intermediary `StateSyncRoot` and `StateSyncChild` contracts. See this (awful) figure, if it helps:
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/2564234/232802749-c8c30927-2296-46f2-8509-f81155b48876.png">

This design would imply the deployment of a pair of contracts for each layer 2 (e.g., for Matic:`StateSyncRootMatic` on Mainnet and `StateSyncChildMatic` on Matic), where each pair implements the most suitable cross-chain mechanism for that particular layer 2.

The CBD application contract would have a mapping of `uint256 => StateSyncRoot`, with chainIDs as keys.
Each L2 Coordinator contract would have a static reference to their corresponding `StateSyncChild`.

**Comment by cygnusv** [comment]
As a reference, OpenZeppelin seems to have a cross-chain functionality for Polygon, Arbitrum and Optimism. See https://docs.openzeppelin.com/contracts/4.x/api/crosschain

**Comment by theref** [comment]
Initial testing is occurring in PR https://github.com/nucypher/nucypher-contracts/pull/71

**Comment by theref** [comment]
Useful Links:
[Polygon Custom Fx Tunnel docs](https://wiki.polygon.technology/docs/develop/l1-l2-communication/fx-portal/)

**Comment by theref** [comment]
Thought about minimising cost...

This needs to be a push based protocol. We're going to be looking up whether operator addresses are authorised quite a lot, ideally it should be free, which means no state changes.
Therefore, whenever the underlying state *does* change (unbond, new stake etc), it needs to trigger updates, ie, push that from eth to polygon/optimism

**Comment by cygnusv** [comment]
Correct, it's a push from L1 to L2. The idea is to have a stake information "cache" in L2 that's updated from L1 when changes occur

**Comment by theref** [comment]
ok, small test of L1 -> L2 (polygon) is working. Goerli contract is [here](https://goerli.etherscan.io/address/0x28C35644F713c7Ee5C6A105e7AB0Fc144889a1Af) and Mumbai contract is [here](https://mumbai.polygonscan.com/address/0x899B961131f0503572F4E9E25904D2c6940D286F)

[This](https://goerli.etherscan.io/tx/0x6a8bbccf7d25b8a4c53e40eece9c941c1c78807595eb317266d78b7414f6074c) transaction sends a message from the root to the child. 20 mins later, [this](https://mumbai.polygonscan.com/tx/0x0d72f856f94a48d0af13f02e12d1e7108cad89316b30c75b1c038ad9d1c4e5c3#eventlog) transaction appears on mumbai and the event log shows the correct sender & receiver.

On the child mumbai contract, we can then see that `latestData`, `latestSateId`, and `latestRootMessageSender` have all been updated.

**Comment by derekpierre** [comment]
Related to [#76 ](https://github.com/nucypher/nucypher-contracts/pull/76)

**Comment by piotr-roslaniec** [comment]
@theref Would you say this is closed by #76?

**Comment by cygnusv** [comment]
Not yet, we need the CBD app to be aware of this

**Comment by derekpierre** [comment]
Is this closed by @vzotova 's recent changes? #99  and others?
