### ISSUE TITLE
Set participant public key during transcript aggregations

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher-contracts#95]
An additional idea from a discussion with @KPrasch: what a about adding the ritual public key as part of the post transcript TX? 

* Piggy-backing from the post transcript TX simplifies things, maybe we can make it an optional parameter in case the the node needs to set the key. Less TXs means simpler client code, less problems.
* Prepares API for when/if Ferveo keys are generated per-ritual.
* Code definitely would look uglier, but I think this is bearable considering Coordinator is for the private beta release.

If this sounds good, we can do this in a separate PR, no need to do it here.

_Originally posted by @cygnusv in https://github.com/nucypher/nucypher-contracts/pull/77#pullrequestreview-1519224421_

**Comment by cygnusv** [comment]
Closing this for the moment, as we're going to use the setting of participants' public keys as evidence of correct operator set up.

**Comment by piotr-roslaniec** [comment]
@cygnusv This was already implemented and merged in https://github.com/nucypher/nucypher-contracts/pull/77
The work on integrating this into `nucypher` continues here: https://github.com/nucypher/nucypher/pull/3188

Sorry, I forgot to close this issue

**Comment by cygnusv** [comment]
My understanding is that #77 added the public key requirement as a separate TX from posting transcripts, and this issue was proposing to unify them. But after recent discussions with @vzotova, we decided to keep them separate, so that's why this issue is being closed now.
